os: linux
language: rust
rust:
  - nightly
dist: bionic

git:
  depth: false

cache:
  directories:
    - ${HOME}/dependencies
    - ${HOME}/Downloads
    - ${TRAVIS_BUILD_DIR}/liboffkv
  cargo: true

jobs:
  include:
    - os: linux
      dist: bionic
      env:
        - VCPKG_TRIPLET="x64-linux"
        - VCPKG_BOOT_EVAL="./bootstrap-vcpkg.sh -disableMetrics"
        - SYSTEM_TRIPLET="linux"
        - PREFERRED_ARCHIVE_EXTENSION="tar.gz"
        - BADGE=linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - cmake
            - pkg-config
            - libssl-dev
    - os: osx
      osx_image: xcode10.2
      env:
        - VCPKG_BOOT_EVAL="./bootstrap-vcpkg.sh -disableMetrics"
        - SYSTEM_TRIPLET="darwin"
        - PREFERRED_ARCHIVE_EXTENSION="zip"
        - BADGE=osx
      addons:
        homebrew:
          packages:
            - gcc@8
          update: true
    # - os: windows
    #   env:
    #     - VCPKG_TRIPLET=x64-windows
    #     - VCPKG_BOOT_EVAL="./bootstrap-vcpkg.bat"
    #     - SYSTEM_TRIPLET=windows
    #     - PREFERRED_ARCHIVE_EXTENSION=zip

before_install:
  - export USE_CLANG="export CC=clang && export CXX=clang++"
  - export USE_GCC="export CC=gcc-8 && export CXX=g++-8"
  - export RUST_BACKTRACE=1
  - export VCPKG_ROOT="$HOME/vcpkg"
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then eval "$USE_GCC"; else eval "$USE_CLANG"; fi

before_script:
  - curl -sL https://github.com/offscale/kv-travis-scripts/archive/master.zip | jar xv
  - mv kv-travis-scripts-master "$HOME/scripts"
  - pushd "$HOME/scripts"
  - chmod +x *.bash
  - ./prepare_vcpkg.bash "$HOME/vcpkg/" "$VCPKG_BOOT_EVAL"
  - ./bootstrap_etcd.bash "$SYSTEM_TRIPLET" "$PREFERRED_ARCHIVE_EXTENSION"
  - ./bootstrap_consul.bash "$SYSTEM_TRIPLET"
  - ./bootstrap_zk.bash
  - popd
  - pushd "$HOME/vcpkg"
  - travis_wait 30 ./vcpkg upgrade --no-dry-run
  - travis_wait 25 ./vcpkg install gtest || "$HOME/scripts/export_vcpkg_logs.bash"
  - travis_wait 34 ./vcpkg install ppconsul || "$HOME/scripts/export_vcpkg_logs.bash"
  - travis_wait 25 ./vcpkg install zkpp || "$HOME/scripts/export_vcpkg_logs.bash"
  - travis_wait 35 ./vcpkg install offscale-libetcd-cpp || "$HOME/scripts/export_vcpkg_logs.bash"
  - rm -rf buildtrees
  - popd

script:
  - cargo build
  - cargo test

before_cache:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then cargo install cargo-tarpaulin; fi

after_failure:
  - "$HOME/scripts/send_status_message.bash"

after_success:
  - |
    if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      export LD_LIBRARY_PATH="$(dirname
        $(find ${TRAVIS_BUILD_DIR} -name libliboffkv_c.so -print -quit)):
        ${VCPKG_ROOT}/installed/${VCPKG_TRIPLET}/lib"
      cargo tarpaulin --out Xml --run-types Doctests
      bash <(curl -s https://codecov.io/bash)
    fi

deploy:
  provider: cargo
  token:
    secure: DIJusjWt/24kP1wbE9R5bpaDkjODIaGE6nTuHGTG/Os2ir0UYolfGy3MsiZKgv/qE2LoOlig1Gb2qcdC4bLDOmiGRPMH5VhiWz4Z+e22yp9Zqu1cjCJgcwqGnM4QFf5L3AMhPCPoI1hpGHgPiXCZ4O1sQtc7E+hJqNGojHjwNna4ZGx0ugJfdBu4lREDgaRjjGKmdUmD+mBWkrqKGfEJTIVxuJxtvdLh4Kc3epJuPwYhBHj8fxMy6i7Ez8wu+zw8rw3V+k/yjkXBV8FtCzoexN2vxXXcWVmVbbvFkbvE7Q829bz22IUkd/sTpRL09YNUbC25SWrzuUs5PvABA9bkyHfu9Q47CvZm7Nlc+c+o1KjiCDAuh4ObSL43I930MsRz0NuLWOO6dPc/UDf9l5TxGAnzoJp3nXA+ro7fVWKbKqLvwVVOIFwDRVeBnI35v435g0Tq52IadTyQyVz0Oej/xS6gbBGouVLq+5NfV46XMAotx4dPnaKqf4bPJIc8+LwpN1UTGNeGTSlhOGQwX96fylryY1R6LCrjH3X+v3j0rYuCpaiblcnZdk9DK1U5zmThMVqWY+SYdOiv3XNdbyoUTYfmreBIdg5nPa21obIRRcwtodPUKRxZ3ZxrFY/uI+3dUfB7Nojc7eEdRr7v40c/mUgiAl5w0eW1tDuqdMiLUMM=
  on:
    branch: master
    condition: $TRAVIS_OS_NAME = linux
