language: rust
rust:
  - stable

deploy:
  provider: cargo
  token:
    secure: DIJusjWt/24kP1wbE9R5bpaDkjODIaGE6nTuHGTG/Os2ir0UYolfGy3MsiZKgv/qE2LoOlig1Gb2qcdC4bLDOmiGRPMH5VhiWz4Z+e22yp9Zqu1cjCJgcwqGnM4QFf5L3AMhPCPoI1hpGHgPiXCZ4O1sQtc7E+hJqNGojHjwNna4ZGx0ugJfdBu4lREDgaRjjGKmdUmD+mBWkrqKGfEJTIVxuJxtvdLh4Kc3epJuPwYhBHj8fxMy6i7Ez8wu+zw8rw3V+k/yjkXBV8FtCzoexN2vxXXcWVmVbbvFkbvE7Q829bz22IUkd/sTpRL09YNUbC25SWrzuUs5PvABA9bkyHfu9Q47CvZm7Nlc+c+o1KjiCDAuh4ObSL43I930MsRz0NuLWOO6dPc/UDf9l5TxGAnzoJp3nXA+ro7fVWKbKqLvwVVOIFwDRVeBnI35v435g0Tq52IadTyQyVz0Oej/xS6gbBGouVLq+5NfV46XMAotx4dPnaKqf4bPJIc8+LwpN1UTGNeGTSlhOGQwX96fylryY1R6LCrjH3X+v3j0rYuCpaiblcnZdk9DK1U5zmThMVqWY+SYdOiv3XNdbyoUTYfmreBIdg5nPa21obIRRcwtodPUKRxZ3ZxrFY/uI+3dUfB7Nojc7eEdRr7v40c/mUgiAl5w0eW1tDuqdMiLUMM=

cache:
  directories:
    - $HOME/vcpkg

matrix:
  include:
    - os: linux
      sudo: true
      env:
        - VCPKG_TRIPLET=x64-linux
        - MATRIX_EVAL="export CC=gcc-8 && export CXX=g++-8"
        - VCPKG_BOOT_EVAL="./bootstrap-vcpkg.sh"
        - SYSTEM_TRIPLET=linux
        - PREFERED_ARCHIVE_EXTENSION=tar.gz
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - cmake
#    - os: osx
#      osx_image: xcode10.2
#      env:
#        - MATRIX_EVAL="brew install gcc@7"
#        - OSX_ENABLE_GCC="CC=gcc-7 && CXX=g++-7"
#        - OSX_ENABLE_CLANG="CC=clang && CXX=clang++"
#        - VCPKG_BOOT_EVAL="./bootstrap-vcpkg.sh"
#        - SYSTEM_TRIPLET=darwin
#        - PREFERED_ARCHIVE_EXTENSION=zip
#      sudo: true

before_install:
  - eval "${MATRIX_EVAL}"
  - eval "$OSX_ENABLE_GCC"

before_script:
  - chmod ug+x ${TRAVIS_BUILD_DIR}/travis/*.sh
  - ${TRAVIS_BUILD_DIR}/travis/prepare_vcpkg.sh "${HOME}/vcpkg/" "${VCPKG_BOOT_EVAL}"
  - cp -r "$TRAVIS_BUILD_DIR/liboffkv/vcpkg/ports" "$HOME/vcpkg/"
  - cd "${HOME}/vcpkg"
  - travis_wait 30 ./vcpkg upgrade --no-dry-run
  - eval "${OSX_ENABLE_CLANG}"
  - travis_wait 34 ./vcpkg install ppconsul || ${TRAVIS_BUILD_DIR}/travis/export_vcpkg_logs.sh
  - travis_wait 25 ./vcpkg install zkpp || ${TRAVIS_BUILD_DIR}/travis/export_vcpkg_logs.sh
  - travis_wait 35 ./vcpkg install offscale-libetcd-cpp || ${TRAVIS_BUILD_DIR}/travis/export_vcpkg_logs.sh
  - sleep 10
  - rm -rf buildtrees
  - cd ${TRAVIS_BUILD_DIR}

script:
  - cargo build
  - ${TRAVIS_BUILD_DIR}/travis/bootstrap_etcd.sh "${SYSTEM_TRIPLET}" "${PREFERED_ARCHIVE_EXTENSION}"
  - ${TRAVIS_BUILD_DIR}/travis/bootstrap_consul.sh "${SYSTEM_TRIPLET}"
  - ${TRAVIS_BUILD_DIR}/travis/bootstrap_zk.sh
  - cargo test
