language: rust
rust:
  - nightly
dist: xenial

deploy:
  provider: cargo
  token:
    secure: DIJusjWt/24kP1wbE9R5bpaDkjODIaGE6nTuHGTG/Os2ir0UYolfGy3MsiZKgv/qE2LoOlig1Gb2qcdC4bLDOmiGRPMH5VhiWz4Z+e22yp9Zqu1cjCJgcwqGnM4QFf5L3AMhPCPoI1hpGHgPiXCZ4O1sQtc7E+hJqNGojHjwNna4ZGx0ugJfdBu4lREDgaRjjGKmdUmD+mBWkrqKGfEJTIVxuJxtvdLh4Kc3epJuPwYhBHj8fxMy6i7Ez8wu+zw8rw3V+k/yjkXBV8FtCzoexN2vxXXcWVmVbbvFkbvE7Q829bz22IUkd/sTpRL09YNUbC25SWrzuUs5PvABA9bkyHfu9Q47CvZm7Nlc+c+o1KjiCDAuh4ObSL43I930MsRz0NuLWOO6dPc/UDf9l5TxGAnzoJp3nXA+ro7fVWKbKqLvwVVOIFwDRVeBnI35v435g0Tq52IadTyQyVz0Oej/xS6gbBGouVLq+5NfV46XMAotx4dPnaKqf4bPJIc8+LwpN1UTGNeGTSlhOGQwX96fylryY1R6LCrjH3X+v3j0rYuCpaiblcnZdk9DK1U5zmThMVqWY+SYdOiv3XNdbyoUTYfmreBIdg5nPa21obIRRcwtodPUKRxZ3ZxrFY/uI+3dUfB7Nojc7eEdRr7v40c/mUgiAl5w0eW1tDuqdMiLUMM=
  on:
    branch: master
    condition: $TRAVIS_OS_NAME = linux

env:
  global:
    # replace it after release with zkpp port
    - VCPKG_VERSION="d1b89575bd2945e5a4fc54dca484a6f86112d33e"
    - VCPKG_TAR_HASH="0c3796ca7393dce5f1fcf19e3d651dcf933114f726b084f4bf58b65ca540834c"
    - VCPKG_ZIP_HASH="2f3497d73b587f6958b7a23d949cb89a9efb0cd3ddbc1ab44899f41cad3810c2"
    - VCPKG_ROOT="${HOME}/dependencies/vcpkg"
    - CMAKE_USE_CLANG="export CC=clang && export CXX=clang++"
    - CMAKE_USE_GCC="export CC=gcc-8 && export CXX=g++-8"
    - RUST_BACKTRACE=1

jobs:
  include:
    - os: linux
      env:
        - VCPKG_TRIPLET=x64-linux
        - SYSTEM_TRIPLET=linux
        - PREFERED_ARCHIVE_EXTENSION=tar.gz
        - ARCHIEVE_EXTRACTOR='tar -xzvf'
        - BADGE=linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - cmake
            - pkg-config
            - libssl-dev
    - os: osx
      osx_image: xcode10.2
      env:
        - SYSTEM_TRIPLET=darwin
        - PREFERED_ARCHIVE_EXTENSION=zip
        - ARCHIEVE_EXTRACTOR='unzip -a'
        - BADGE=osx

before_install:
  - chmod ug+x ${TRAVIS_BUILD_DIR}/travis/*.sh

  - |
    case "${PREFERED_ARCHIVE_EXTENSION}" in
      zip) VCPKG_HASH="${VCPKG_ZIP_HASH}" ;;
      *) VCPKG_HASH="${VCPKG_TAR_HASH}" ;;
    esac

install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install gcc@8 && brew unlink gcc && brew link gcc@8; fi

  - mkdir -p "${HOME}/dependencies" && cd "${HOME}/dependencies"

  - vcpkg_archive="${VCPKG_VERSION}.${PREFERED_ARCHIVE_EXTENSION}"
  - |
    if ! test -f "${vcpkg_archive}" ||
        [[ ! $(sha256sum "${vcpkg_archive}" | cut -d' ' -f1) = "${VCPKG_HASH}" ]];
    then
      wget "https://github.com/microsoft/vcpkg/archive/${vcpkg_archive}"
      if [[ ! $(sha256sum "${vcpkg_archive}" | cut -d' ' -f1) = ${VCPKG_HASH} ]]; then exit 1; fi
      ${ARCHIEVE_EXTRACTOR} "${vcpkg_archive}"
      rm -rf ${VCPKG_ROOT}
      mv vcpkg-${VCPKG_VERSION} ${VCPKG_ROOT}
    fi

  - cd ${VCPKG_ROOT}

  - eval ${CMAKE_USE_GCC}
  - ./bootstrap-vcpkg.sh
  - travis_wait 30 ./vcpkg upgrade --no-dry-run

  - eval ${CMAKE_USE_CLANG}
  - travis_wait 30 ./vcpkg install ppconsul
  - travis_wait 30 ./vcpkg install zkpp
  - travis_wait 30 ./vcpkg install offscale-libetcd-cpp
  - sleep 10

  - rm -rf buildtrees
  - cd ${TRAVIS_BUILD_DIR}

script:
  - cargo build

  - ${TRAVIS_BUILD_DIR}/travis/bootstrap_etcd.sh ${SYSTEM_TRIPLET} ${PREFERED_ARCHIVE_EXTENSION}
  - ${TRAVIS_BUILD_DIR}/travis/bootstrap_consul.sh ${SYSTEM_TRIPLET}
  - ${TRAVIS_BUILD_DIR}/travis/bootstrap_zk.sh

  - cargo test

before_cache:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then cargo install cargo-tarpaulin; fi

after_success:
  - |
    if [ "$TRAVIS_OS_NAME" = "linux" ];
    then
      export LD_LIBRARY_PATH="$(dirname
        $(find ${TRAVIS_BUILD_DIR} -name libliboffkv_c.so -print -quit)):
        ${VCPKG_ROOT}/installed/${VCPKG_TRIPLET}/lib"
      cargo tarpaulin --out Xml --run-types Doctests
      bash <(curl -s https://codecov.io/bash)
    fi

cache:
  directories:
    - ${HOME}/dependencies
    - ${TRAVIS_BUILD_DIR}/liboffkv
  cargo: true
